### ISSUE TITLE
Wifi firmware fails to load on Debian linux

### ISSUE THREAD

**Issue by UtsavBalar1231** [SiliconLabs/wfx-linux-driver#2]
Greetings, I am facing this weird issue where the firmware and fallback firmware is already present. But, the sdio wfx is unable to load the firmware and returns error.

Kernel logs from linux revision 5.10.X with the latest drivers and firmware
```
root@linaro-alip:~# dmesg | grep sdio
[    2.846992] wfx: sdio_register_driver() returned 0
[    2.889098] wfx-sdio mmc2:0001:1: probe
[    2.889222] wfx-sdio mmc2:0001:1: sdio_enable_func: 0
[    2.892797] wfx-sdio mmc2:0001:1: can't load wfx/wfm_wf200_C0.sec, falling back to wfx/wfm_wf200.sec
[    2.892881] wfx-sdio mmc2:0001:1: Direct firmware load for wfx/wfm_wf200.sec failed with error -2
[    2.892888] wfx-sdio mmc2:0001:1: can't load wfx/wfm_wf200.sec
[    2.893000] wfx-sdio mmc2:0001:1: failed to initialize device: -2
[    2.893016] wfx-sdio mmc2:0001:1: wfx_probe failed
[    2.893021] wfx-sdio mmc2:0001:1: failed sdio release
[    2.893095] wfx-sdio: probe of mmc2:0001:1 failed with error -2
```

The firmware files are present
```
root@linaro-alip:~# ls /lib/firmware/wfx/
wf200.pds  wfm_wf200.sec  wfm_wf200_C0.sec
```

Below is my sdio configuration of a reference RK3399Pro board
```

&sdio0 {
	clock-frequency = <50000000>;
	clock-freq-min-max = <200000 50000000>;
	max-frequency = <50000000>;
	supports-sdio;
	bus-width = <4>;
	disable-wp;
	cap-sd-highspeed;
	cap-sdio-irq;
	keep-power-in-suspend;
	mmc-pwrseq = <&sdio_pwrseq>;
	non-removable;
	num-slots = <1>;
	pinctrl-names = "default";
	pinctrl-0 = <&sdio0_bus4 &sdio0_cmd &sdio0_clk>;
	#address-cells = <1>;
	#size-cells = <0>;
	status = "okay";

	wf200: mmc@1 {
		compatible = "silabs,wf200";
		reg = <1>;
		pinctrl-names = "default";
		pinctrl-0 = <&bt_wake_pin>;
		wakeup-gpios = <&gpio2 RK_PD2 GPIO_ACTIVE_HIGH>;
		config-file = "wf200.pds";
	};
};
```

Please guide me if there is some mistake that I might have made.

**Comment by jerome-pouiller** [comment]
Maybe `/lib/firmware/wfx/` didn't exist (= was not mounted) when the driver was loaded. Can you check if you get the same error if you [bind the device again][1]

[1]: https://github.com/SiliconLabs/wfx-linux-driver?tab=readme-ov-file#reset-device-without-rebooting-target

**Comment by UtsavBalar1231** [comment]
> Maybe `/lib/firmware/wfx/` didn't exist (= was not mounted) when the driver was loaded. Can you check if you get the same error if you [bind the device again](https://github.com/SiliconLabs/wfx-linux-driver?tab=readme-ov-file#reset-device-without-rebooting-target)

Thanks it works after resetting the sdio bus.

**Comment by jerome-pouiller** [comment]
An idea why `/lib/firmware/wfx/` do not exist? Do you think `wfx.ko` has been included in initramfs? In this case, maybe declaring the firmware with `MODULE_FIRMWARE()` would solve the issue?

**Comment by jerome-pouiller** [comment]
Can you try this patch:
```[patch]
diff --git i/main.c w/main.c
index bba2dd29..4a4b3b36 100644
--- i/main.c
+++ w/main.c
@@ -48,6 +48,8 @@ MODULE_VERSION(WFX_LABEL "-internal");
 #else
 MODULE_VERSION(WFX_LABEL);
 #endif
+MODULE_FIRMWARE("wfx/wfm_wf200_C0.sec")
+MODULE_FIRMWARE("wfx/wfm_wf200.sec")
 
 #define RATETAB_ENT(_rate, _rateid, _flags) { \
 	.bitrate  = (_rate),   \
```

**Comment by UtsavBalar1231** [comment]
@jerome-pouiller I can confirm that when this driver is built-in inside kernel image it is unable to find the firmware. But, when built as module the firmware loads just fine.

So, issue is with the time at which SDIO driver registers and get_firmware is executed.

**Comment by jerome-pouiller** [comment]
Does the patch above fix the issue?

**Comment by UtsavBalar1231** [comment]
Hey @jerome-pouiller sorry for the delay. But, the above patch does not fix this issue.
Here are the kernel logs, added module_firmware macro as per your patch.
 
```text
[    2.577542] wfx: Silicon Labs 2.14.1
[    2.631720] mmc_host mmc2: card is non-removable.
[    2.643553] mmc_host mmc2: Bus speed (slot 0) = 400000Hz (slot req 400000Hz, actual 400000HZ div = 0)
[    2.672130] mmc_host mmc2: Bus speed (slot 0) = 50000000Hz (slot req 50000000Hz, actual 50000000HZ div = 0)
[    2.673315] mmc2: new high speed SDIO card at address 0001
[    2.676620] wfx-sdio mmc2:0001:1: can't load wfx/wfm_wf200_C0.sec, falling back to wfx/wfm_wf200.sec
[    2.676712] wfx-sdio mmc2:0001:1: Direct firmware load for wfx/wfm_wf200.sec failed with error -2
[    2.676720] wfx-sdio mmc2:0001:1: can't load wfx/wfm_wf200.sec
[    2.676896] wfx-sdio: probe of mmc2:0001:1 failed with error -2
```

Can still confirm that building as module works fine, just not inlined
